language: java
jdk:
    - openjdk8
addons:
    sonarcloud:
        organization: dropmino
        token:
            secure: 2955e8e6106e54c9996e362db80d08bfbb84e19c
script:
    - ant build
    - sonar-scanner
